### ISSUE TITLE
Scrolling creates error with wasm version mismatch

### ISSUE THREAD

**Issue by lalalune** [webaverse-studios/webaverse#55]
**Describe the bug**
When I try to scroll it throws an error. Seems to be some kind of issue with wasm.

![image](https://user-images.githubusercontent.com/18633264/213421669-bb7499d4-10e1-483c-9f57-c8923c4073be.png)

**Comment by gonnavis** [comment]
Got it, let me check.

**Comment by lalalune** [comment]
Seems to be ok now
