### ISSUE TITLE
Exported vrm models have bent hands while running, gliding etc

### ISSUE THREAD

**Issue by alisaad673** [webaverse-studios/webaverse#82]
While we export a vrm character and drag and drop into webaverse engine. The hands get bended while running and gliding.

https://user-images.githubusercontent.com/35926530/214877748-e89aee3a-8c7e-4649-b0ac-8b70a658a19a.mp4

![image (2)](https://user-images.githubusercontent.com/35926530/214877559-1a8dfd29-1766-49eb-bf03-136cc3c9f85c.png)

https://user-images.githubusercontent.com/35926530/214877616-63454b5b-e8b5-4c14-8d35-cb29549c16b2.mp4

**Comment by soulofmischief** [comment]
@gonnavis moved to monorepo for tracking, plz close when ported!

**Comment by gonnavis** [comment]
Got it! I'm porting.

**Comment by gonnavis** [comment]
Ported, tested, and merged.
