### ISSUE TITLE
Infinifruit eat animation sync issue

### ISSUE THREAD

**Issue by alisaad673** [webaverse-studios/webaverse#90]
**Describe the bug**
While we try to eat infinifruit in one go, the animation seems to be in sync with the fruit. But when we don't eat the fruit in one go, and try to eat it in steps, the last go, keeps playing the whole eat animation instead even if the fruit is finished already.

**To Reproduce**
1. Go to treehouse.scn
2. pickup infinifruit
3. press LMB once to eat fruit, press it again once
4. press and hold LMB untill fruit is finished and animation stops playing

https://user-images.githubusercontent.com/35926530/216396491-55c75851-4be9-4ec8-8b8d-6a7b3e353e90.mp4

https://user-images.githubusercontent.com/35926530/216396502-706d3f72-474a-4921-bb75-c666b9f2a5ac.mp4

**Comment by tcm390** [comment]
fixed by this PR https://github.com/webaverse/infinifruit/pull/7
